# Generated by Django 3.0.8 on 2020-07-31 15:12

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion
import sitealias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain name')),
                ('name', models.CharField(max_length=50, verbose_name='display name')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Parent Site')),
            ],
            options={
                'verbose_name': 'site alias',
                'verbose_name_plural': 'site aliases',
                'ordering': ['site', 'domain'],
            },
            managers=[
                ('objects', sitealias.models.SiteAliasManager()),
            ],
        ),
    ]
