# Generated by Django 3.1.6 on 2021-02-03 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitealias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitealias',
            name='domain',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.URLValidator(schemes=['https'])], verbose_name='domain name'),
        ),
        migrations.AlterField(
            model_name='sitealias',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='display name'),
        ),
    ]
