# Generated by Django 3.1.13 on 2021-09-20 13:19

import django.contrib.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitealias', '0002_auto_20210203_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitealias',
            name='domain',
            field=models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain name'),
        ),
    ]
